version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SOLVER_API_URL=http://localhost:8000
    depends_on:
      - solver
    networks:
      - motion-network
    restart: unless-stopped

  # FastAPI Solver Service
  solver:
    build:
      context: ./solver
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    networks:
      - motion-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  motion-network:
    driver: bridge

# Development override file can be created as docker-compose.override.yml